""" analyze the data files generated by lexical decision """

import sys
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv(sys.argv[1], comment='#')

data = data.loc[data.category != 'PSEUDO']  # exclude pseudowords

# detailed plot
sns.catplot(x='category', y='rt', hue='frequency', data=data)
plt.show()

# effects of frequency (hi vs. lo) and  category (noun vs verb)
sns.catplot(x="frequency", y='rt', col="category",
                data=data,
                kind="bar", height=2.5, aspect=.8)
plt.show()

# Anova on Log Reaction Times with Frequency and Category as predictors 
from statsmodels.formula.api import ols
import statsmodels.api as sm

data['logrt']=np.log10(data['rt'])
print(data.groupby(['category','frequency']).describe())

anova_logrt = ols('logrt ~ frequency * category', data=data).fit()
table = sm.stats.anova_lm(anova_logrt)
print(table)
